"""empty message

Revision ID: 645f1a359963
Revises: 
Create Date: 2019-01-15 18:36:41.731872

"""
from alembic import op
import sqlalchemy as sa
from ecom.models import custom_datatypes


# revision identifiers, used by Alembic.
revision = '645f1a359963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', custom_datatypes.UUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_table('subscription_members',
    sa.Column('id', custom_datatypes.UUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('subscription_id', custom_datatypes.UUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_members_created_at'), 'subscription_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_members_mobile'), 'subscription_members', ['mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_members_mobile'), table_name='subscription_members')
    op.drop_index(op.f('ix_subscription_members_created_at'), table_name='subscription_members')
    op.drop_table('subscription_members')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
